version: '3.7'

services:
  common_redis:
    hostname: common_redis
    container_name: common_redis
    image: redis:alpine
    ports:
      - '6379:6379'
    networks:
      - local

networks:
  local:
    name: local
